version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11.1-stretch

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: yarn test
      - run: docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_PASSWORD
      - run:
        name: "Build docker image and push to docker hub"
        command: |
          cp Dockerfile.production Dockerfile
          docker build -t warisr/example-nodejs-circle:latest .
          docker build -t warisr/example-nodejs-circle:${CIRCLE_SHA1} .
          docker push warisr/example-nodejs-circle:latest
          docker push warisr/example-nodejs-circle:${CIRCLE_SHA1}
      - run: echo Done

